---
- name: User choices
  hosts: kali
  vars:
  tasks:
    - name: Get user details
      user:
        name: "{{ kali_user }}"
      register: kali_user_details

    - name: Check if .a4k_config.yml exists
      ansible.builtin.stat:
        path: "{{ kali_user_details.home }}/.a4k_config.yml"
      register: config_yml

    - name: Load .a4k_config.yml
      ansible.builtin.include_vars: "{{ kali_user_details.home }}/.a4k_config.yml"
      when: config_yml.stat.exists

    - name: Save config
      ansible.builtin.template:
        src: templates/config/config.yml.j2
        dest: "{{ kali_user_details.home }}/.a4k_config.yml"
        mode: 0600

- name: Include Kali packages playbook
  ansible.builtin.import_playbook: kali-packages.yml

- name: Include Kali tools playbook
  ansible.builtin.import_playbook: kali-tools.yml

- name: Include Kali configuration playbook
  ansible.builtin.import_playbook: kali-config.yml

- name: Include Kali personalization playbook
  ansible.builtin.import_playbook: kali-personalize.yml
